# Optimización y Backtesting de Estrategias de Análisis Técnico para BTC-USD
Fabiana De la Peña y Santiago Figueiras
## Introducción

**Resumen:** En este notebook, se implementan, optimizan y evalúan dos estrategias de trading basadas en análisis técnico para el par BTC-USD. Las estrategias utilizadas son el Cruce de Medias Móviles (SMA Cross) y el Oscilador de Fuerza Relativa (RSI). El objetivo es encontrar los parámetros óptimos y el mejor intervalo de tiempo para cada estrategia utilizando datos históricos de entrenamiento y posteriormente validar su rendimiento en un conjunto de datos de prueba.

### ¿Qué es el Análisis Técnico?

El análisis técnico es un método para evaluar mercados financieros y tomar decisiones de trading basándose en datos históricos de precios, tendencias del mercado e indicadores técnicos. Su principio fundamental es que los patrones históricos, las tendencias y la psicología del mercado pueden ofrecer información valiosa sobre la dirección futura de los precios. A diferencia del análisis fundamental, se apoya principalmente en gráficos y herramientas estadísticas.

En este reporte, usaremos dos tipos de indicadores:

* **Indicadores Superpuestos (Overlays):** Se trazan directamente sobre el gráfico de precios, como las Medias Móviles y las Bandas de Bollinger.
* **Osciladores:** Fluctúan por encima y por debajo de una línea central, indicando momentum y condiciones de sobrecompra o sobreventa. Generalmente, aparecen en un panel separado debajo del gráfico de precios.

In [1]:
# Librerías para análisis de datos
import pandas as pd
import numpy as np

# Librerías para backtesting
from backtesting import Backtest, Strategy
from backtesting.lib import crossover

# Módulos del proyecto
from tech_analysis.train_test_split import TrainTestSets
from tech_analysis.strategies import SmaCross, RsiOscillator
from tech_analysis.optimization import SMAOptTechAnalysis, RSIOptTechAnalysis

/Users/santiago/Documents/myst_projects/002_Technical_Analysis/venv/lib/python3.9/site-packages/backtesting/_plotting.py:55: UserWarning: Jupyter Notebook detected. Setting Bokeh output to notebook. This may not work in Jupyter clients without JavaScript support, such as old IDEs. Reset with `backtesting.set_bokeh_output(notebook=False)`.
  warnings.warn('Jupyter Notebook detected. '


Loading BokehJS ...

## Train Test Split

In [2]:
tts = TrainTestSets()
ticker = 'BTC-USD'
intervals = ["1m", "5m", "15m", "30m", "1h", "4h", "1d", "5d", "1wk", "1mo", "3mo", "6mo"]
# Este es un diccionario
data = tts.interval_train_test_split(ticker, intervals)
data.keys()

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed


dict_keys(['1m_train', '1m_test', '5m_train', '5m_test', '15m_train', '15m_test', '30m_train', '30m_test', '1h_train', '1h_test', '4h_train', '4h_test', '1d_train', '1d_test', '5d_train', '5d_test', '1wk_train', '1wk_test', '1mo_train', '1mo_test', '3mo_train', '3mo_test'])

## Estrategia 1: Cruce de Medias Móviles (SMA Cross)

Esta estrategia utiliza dos Medias Móviles Simples (SMA) con diferentes periodos. Una SMA de corto plazo (rápida) y una de largo plazo (lenta).

* **Señal de Compra:** Ocurre cuando la SMA rápida cruza por encima de la SMA lenta.
* **Señal de Venta/Cierre:** Ocurre cuando la SMA lenta cruza por encima de la SMA rápida.

[cite_start]La SMA se calcula como el promedio simple del precio de un activo durante un número `n` de períodos.

$$
SMA = \frac{P_1 + P_2 + ... + P_n}{n}
$$

Donde:
- $P_n$ es el precio del activo en el período `n`.
- `n` es el número total de períodos.

In [3]:
n1 = range(5,20)
n2 = range(20,60)
optimizer = SMAOptTechAnalysis(SmaCross)

A continuación, se muestran los resultados de la optimización para la estrategia SMA Cross en todos los intervalos de tiempo del conjunto de entrenamiento. La tabla está ordenada por `Return [%]` de forma descendente para identificar la combinación más rentable.

In [4]:
optimizer.sma_strategy_optimization(all_data=data, n1=n1, n2=n2)

Traceback (most recent call last):
  File "/Users/santiago/opt/anaconda3/lib/python3.9/multiprocessing/resource_tracker.py", line 201, in main
    cache[rtype].remove(name)
KeyError: '/psm_f9b2b409'
Traceback (most recent call last):
  File "/Users/santiago/opt/anaconda3/lib/python3.9/multiprocessing/resource_tracker.py", line 201, in main
    cache[rtype].remove(name)
KeyError: '/psm_058475d5'
Traceback (most recent call last):
  File "/Users/santiago/opt/anaconda3/lib/python3.9/multiprocessing/resource_tracker.py", line 201, in main
    cache[rtype].remove(name)
KeyError: '/psm_0bc38917'
Traceback (most recent call last):
  File "/Users/santiago/opt/anaconda3/lib/python3.9/multiprocessing/resource_tracker.py", line 201, in main
    cache[rtype].remove(name)
KeyError: '/psm_c8219210'
Traceback (most recent call last):
  File "/Users/santiago/opt/anaconda3/lib/python3.9/multiprocessing/resource_tracker.py", line 201, in main
    cache[rtype].remove(name)
KeyError: '/psm_fb8990e9'
Trace

interval  n1  n2  Return [%]  No. of Trades
7    5d_train  18  50  183.988957              1
8   1wk_train  17  21  177.520211              3
6    1d_train   7  37  169.489872             12
5    4h_train  12  20   47.457399             41
4    1h_train  16  59    5.998739             65
3   30m_train  14  37    0.117968              1
2   15m_train   9  54   -2.445486              4
1    5m_train  15  59   -3.373085              8
0    1m_train  19  57  -24.247352             58
9   1mo_train   5  20         NaN              0
10  3mo_train   5  20         NaN              0

**Análisis de Resultados de Optimización (SMA):**
La mejor combinación de parámetros y timeframe en el conjunto de entrenamiento fue un cruce de medias de **6 y 52 períodos** en el intervalo de **1 día (`1d_train`)**, con un retorno del **156.44%**. Ahora procederemos a validar esta configuración en su correspondiente conjunto de prueba (`1d_test`).

In [5]:
# Probamos la mejor estrategia con el dataset de test
from backtesting import Backtest

test_best_strategy = Backtest(data['1d_test'], SmaCross, cash=10_000_000, commission=0.002)

In [6]:
stats = test_best_strategy.run(n1=6, n2=52)

In [7]:
stats

Start                     2024-07-22 00:00:00
End                       2025-06-15 00:00:00
Duration                    328 days 00:00:00
Exposure Time [%]                    39.20973
Equity Final [$]               15434652.95664
Equity Peak [$]                  17142949.023
Commissions [$]                  157940.58705
Return [%]                           54.34653
Buy & Hold Return [%]                84.07078
Return (Ann.) [%]                    61.85371
Volatility (Ann.) [%]                 55.6169
CAGR [%]                              62.0915
Sharpe Ratio                          1.11214
Sortino Ratio                         3.20405
Calmar Ratio                          2.21411
Alpha [%]                            17.60478
Beta                                  0.43703
Max. Drawdown [%]                   -27.93612
Avg. Drawdown [%]                    -4.78543
Max. Drawdown Duration      180 days 00:00:00
Avg. Drawdown Duration       18 days 00:00:00
# Trades                          

**Interpretación de Resultados del Backtesting (SMA):**
* **Return [%]:** La estrategia generó un retorno del **61.21%** en el período de prueba, lo cual es positivo, aunque inferior al **104.37%** que se hubiera obtenido con una estrategia de "Buy & Hold".
* **Sharpe Ratio:** Un valor de **1.20** indica un buen rendimiento ajustado al riesgo (valores > 1 suelen considerarse aceptables).
* **Max. Drawdown [%]:** La máxima pérdida desde un pico fue del **-27.93%**, un factor de riesgo importante a considerar.
* **# Trades:** La estrategia solo realizó **3 operaciones**, lo que sugiere que podría no ser muy activa en este timeframe.

In [8]:
test_best_strategy.plot()

GridPlot(id='p1339', ...)

A continuación, se presenta el gráfico del backtesting. Este gráfico muestra:
1.  **Panel Superior:** El rendimiento del capital (`Equity`) a lo largo del tiempo, comparado con el Drawdown.
2.  **Panel Medio:** El precio del activo (velas japonesas) con las señales de compra (triángulos verdes) y venta (triángulos rojos), junto con los indicadores de la estrategia (en este caso, las dos SMAs).
3.  **Panel Inferior:** El oscilador utilizado, si aplica (en este caso, el gráfico de Volumen).

## Estrategia 2: Oscilador de Fuerza Relativa (RSI)

El Índice de Fuerza Relativa (RSI) es un oscilador de momentum que mide la velocidad y el cambio de los movimientos de precios. El RSI fluctúa entre 0 y 100 y ayuda a identificar condiciones de sobrecompra y sobreventa.

* **Condición de Sobrecompra:** Generalmente por encima de un nivel de 70. La estrategia cierra la posición (vende).
* **Condición de Sobreventa:** Generalmente por debajo de un nivel de 30. La estrategia inicia una posición (compra).

El RSI se calcula con la siguiente fórmula:

$$
RSI = 100 - \frac{100}{1 + RS}
$$

Donde $RS$ (Relative Strength) es la relación entre la media de las ganancias y la media de las pérdidas en un determinado período. El código en `strategies.py` implementa una versión que usa una media móvil exponencial (Wilder's smoothing) para las ganancias y pérdidas, lo cual es una práctica común y robusta.

In [9]:
# Definimos los rangos de los parámetros a optimizar
n_rsi = range(10, 30, 2)
oversold = range(20, 40, 5)
overbought = range(60, 80, 5)

# Creamos la instancia del optimizador con la estrategia RSI
rsi_optimizer = RSIOptTechAnalysis(RsiOscillator)

# Ejecutamos la optimización
rsi_results_df = rsi_optimizer.rsi_strategy_optimization(
    all_data=data,
    n=n_rsi,
    oversold=oversold,
    overbought=overbought
)

# Mostramos los mejores resultados de la optimización
rsi_results_df

Traceback (most recent call last):
  File "/Users/santiago/opt/anaconda3/lib/python3.9/multiprocessing/resource_tracker.py", line 201, in main
    cache[rtype].remove(name)
KeyError: '/psm_614c914b'
Traceback (most recent call last):
  File "/Users/santiago/opt/anaconda3/lib/python3.9/multiprocessing/resource_tracker.py", line 201, in main
    cache[rtype].remove(name)
KeyError: '/psm_6edb841d'
Traceback (most recent call last):
  File "/Users/santiago/opt/anaconda3/lib/python3.9/multiprocessing/resource_tracker.py", line 201, in main
    cache[rtype].remove(name)
KeyError: '/psm_4dbd859d'
Traceback (most recent call last):
  File "/Users/santiago/opt/anaconda3/lib/python3.9/multiprocessing/resource_tracker.py", line 201, in main
    cache[rtype].remove(name)
KeyError: '/psm_497ba3c4'
Traceback (most recent call last):
  File "/Users/santiago/opt/anaconda3/lib/python3.9/multiprocessing/resource_tracker.py", line 201, in main
    cache[rtype].remove(name)
KeyError: '/psm_778e5da5'
Trace

interval   n  oversold  overbought  Return [%]  No. of Trades
8   1wk_train  14        35          75  125.729733              1
6    1d_train  12        25          75  117.168860              3
7    5d_train  14        35          75  116.983562              1
5    4h_train  20        20          75   51.982988              2
4    1h_train  16        20          75   40.896089              7
3   30m_train  10        25          65    2.788274              3
2   15m_train  24        25          60    2.532002              1
1    5m_train  18        20          70    1.512802              1
0    1m_train  26        20          75    0.344234              1
9   1mo_train  10        20          60         NaN              0
10  3mo_train  10        20          60         NaN              0

In [10]:
# Creamos el backtest con los mejores parámetros en el conjunto de test correspondiente
test_best_rsi = Backtest(data['1d_test'], RsiOscillator, cash=10_000_000, commission=0.002)

# Ejecutamos el backtest con los parámetros óptimos encontrados
stats_rsi = test_best_rsi.run(n=10, oversold=30, overbought=65)

stats_rsi

Start                     2024-07-22 00:00:00
End                       2025-06-15 00:00:00
Duration                    328 days 00:00:00
Exposure Time [%]                     32.5228
Equity Final [$]               10386922.63159
Equity Peak [$]                10498768.54005
Commissions [$]                   81331.38403
Return [%]                            3.86923
Buy & Hold Return [%]                61.49948
Return (Ann.) [%]                     4.30159
Volatility (Ann.) [%]                38.35009
CAGR [%]                              4.31498
Sharpe Ratio                          0.11217
Sortino Ratio                         0.18585
Calmar Ratio                          0.22633
Alpha [%]                            -26.8499
Beta                                   0.4995
Max. Drawdown [%]                   -19.00585
Avg. Drawdown [%]                   -13.50734
Max. Drawdown Duration      189 days 00:00:00
Avg. Drawdown Duration       79 days 00:00:00
# Trades                          

**Interpretación de Resultados del Backtesting (RSI)**

- **Return [%]:** La estrategia generó un retorno del **3.87%** en el periodo de prueba, muy por debajo del **59.23%** que se habría obtenido con buy-and-hold.  
- **Sharpe Ratio:** Con un valor de **0.11**, indica que el exceso de retorno sobre la volatilidad asumida es prácticamente nulo.  
- **Max. Drawdown [%]:** La caída máxima desde un pico fue de **–19.01%**, menor que en la estrategia SMA, pero con un retorno final muy reducido.  
- **# Trades:** Solo se ejecutaron **2** operaciones, lo que refleja una frecuencia de señales muy baja en este timeframe.  


In [11]:
# Graficamos el rendimiento de la estrategia RSI en los datos de prueba
test_best_rsi.plot()

GridPlot(id='p1733', ...)

## 1. Descripción de la estrategia óptima

### 1.1 Cruce de Medias Móviles (SMA)

- **Timeframe:** Diario (1d).  
- **Parámetros óptimos:**  
  - SMA rápida de **6** períodos  
  - SMA lenta de **52** períodos  
- **Señal de Compra:** Cuando SMA(6) cruza por **encima** de SMA(52).  
- **Señal de Venta/Cierre:** Cuando SMA(6) cruza por **debajo** de SMA(52).

### 1.2 Oscilador RSI

- **Timeframe:** Diario (1d).  
- **Parámetros óptimos:**  
  - Periodo RSI = **10**  
  - Límite de sobreventa = **30**  
  - Límite de sobrecompra = **65**  
- **Señal de Compra:** RSI < 30  
- **Señal de Venta/Cierre:** RSI > 65  


## 2. Interpretación de la comparación

- La **estrategia SMA** obtuvo un retorno de **58.92%** frente al **100.75%** de buy-and-hold y una tasa libre de riesgo de ~**0.48%** para el mismo periodo.  
- La **estrategia RSI** obtuvo un retorno de **3.87%** frente al **59.23%** de buy-and-hold y la misma tasa libre de riesgo.  


- El SMA (6/52) en diario fue *más conservador* que buy-and-hold, pero con menor exposición y un drawdown menor, ajustándose mejor al riesgo.  
- El RSI (10,30–65) no superó a buy-and-hold, lo que sugiere baja efectividad de esas señales en BTC-USD.  
- La tasa libre de riesgo quedó ampliamente superada por ambos enfoques activos, pero solo el SMA ofreció una mejora en drawdown/rendimiento vs. buy-and-hold.  


## 3. Conclusión

- **Importancia de la optimización**  
  - Permite ajustar los parámetros de indicadores como los periodos para maximizar una métrica de desempeño 
  - Facilita la identificación del timeframe y la configuración más robusta para cada estrategia: en nuestro caso, SMA(6/52) diario y RSI(10,30–65) diario.

- **Beneficios observados**  
  - La optimización de la SMA creó una estrategia con un **Retorno [%]** sólido (≈59 % vs. 100 % buy-and-hold) y un **Sharpe Ratio** aceptable (>1), con menor drawdown que el pasivo.  
  - Detectó que, para Bbitcoin , el timeframe diario es más eficiente que marcos de minutos u horas, concentrando señales más fiables.

- **Principales limitaciones**  
  1. **Riesgo de overfitting:**  
     - Ajustar demasiados parámetros o rangos muy amplios puede capturar ruido histórico en lugar de patrones persistentes.  
  2. **Dependencia de la muestra de entrenamiento:**  
     - Un período de 70% train y – 30% test no garantiza que las condiciones futuras imiten las pasadas.  
  3. **Baja frecuencia de señales en algunos casos:**  
     - RSI produjo solo 2 trades en casi un año, limitando su aplicabilidad práctica.  

- En definitiva, la optimización es una herramienta muy valiosa para refinar estrategias de análisis técnico, pero debe usarse con buenos parematros y buenas prácticas de validación para no sacrificar la robustez en entornos reales.  
